export const SHOW_SIGNUP = "SHOW_SIGNUP";
export const SHOW_SIGNIN = "SHOW_SIGNIN";
export const SHOW_AUTH_REQUEST = "SHOW_AUTH_REQUEST";

export const SET_CHAL_INFO_MODAL = "SET_CHAL_INFO_MODAL";

export const SET_POPUP_MODAL = "SET_POPUP_MODAL";

export const CHECK_USER = "CHECK_USER";
export const LOGOUT = "USER_LOGOUT";
export const JOIN_CHALLENGE = "JOIN_CHALLENGE";
export const TOGGLE_SOCKET = "TOGGLE_SOCKET";

export const CURRENT_ROOM = "CURRENT_ROOM";
export const SELECT_ALIEN = "SELECT_ALIEN";
export const GRADUATE_ALIEN = "GRADUATE_ALIEN";
export const THANOS_ALIENS = "THANOS_ALIENS";
export const REQUEST_AUTH = "REQUEST_AUTH";
export const APPROVE_AUTH = "APPROVE_AUTH";

export const MESSAGE_UPDATE = "MESSAGE_UPDATE";
